# Generated by Django 5.0.6 on 2024-06-08 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('cpf_aluno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id_ref', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ref', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id_acesso', models.AutoField(primary_key=True, serialize=False)),
                ('data_acesso', models.DateTimeField(blank=True, null=True)),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='refeitorioApp.aluno')),
                ('id_ref', models.ForeignKey(db_column='id_ref', on_delete=django.db.models.deletion.DO_NOTHING, to='refeitorioApp.refeicao')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('num_matricula', models.CharField(max_length=255)),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='refeitorioApp.aluno')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='refeitorioApp.curso')),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.DO_NOTHING, to='refeitorioApp.turno')),
            ],
        ),
    ]
