# Generated by Django 5.0.6 on 2024-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeitorioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acesso',
            name='nome_acesso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
